#! /usr/bin/bash
#SBATCH --job-name=CIFAR    
#SBATCH --partition=gpu
#SBATCH --exclusive
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20G
#SBATCH --gres gpu:tesla:1
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate ~/anaconda3/envs/cuda_env/
conda activate cuda_env
module load cuda

DIR=''
DATASET='CIFAR'
python $DIR/code/run_models/run.py --dataset=$DATASET --hyperparameter=False
