#! /usr/bin/bash
#SBATCH --job-name=Weather
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=15G
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate
conda activate torch_env

DIR=''
DATASET='Weather'
python $DIR/code/run_models/run.py --dataset=$DATASET --hyperparameter=False
