#! /usr/bin/bash
#SBATCH --job-name=reg
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=40G
#SBATCH --time=40:00:00

source ~/anaconda3/bin/activate
conda activate torch_env

DIR=''
python $DIR/code/regularization_param/reg_param.py
